### ISSUE TITLE
User avatar Id

### ISSUE THREAD

**Issue by martinpppx** [PlayEveryWare/eos_plugin_for_unity#182]
Hey, how can I get the avatar of a specific player? When i was using Facepunch that was method called 'SteamUtils.GetImageSize' -> https://wiki.facepunch.com/steamworks/SteamUtils.GetImageSize
And you can tell me why when i'm using EOSLobbyManager - 'CreateLobby' function callback is executed twice.

**Comment by scovertb** [comment]
It doesn't appear that EOS currently has customizable avatars. It looks like in the EOS friends list they're just the first letter of the user's display name on a colored background.

**Comment by scovertb** [comment]
As to the lobby creation callback, it looks like the callback is called once when CreateLobby is completed and the lobby is created on the backend, then again when UpdateLobby is completed and all of the requested properties of the new lobby have been actually applied. For the sample this is desirable since all the callback does is update the lobby menu UI, but that could potentially be either split into two callbacks or the callback could be delayed until the UpdateLobby call is complete.
