### ISSUE TITLE
AndroidX Property not Enabled

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#185]
**Describe the bug**
When building Android, it throws an error saying `Configuration releaseRuntimeClasspath contains AndroidX dependencies, but the android.useAndroidX property is not enabled, which may cause runtime issues. Set android.useAndroidX=true in the gradle.properties file and retry.`

**To Reproduce**
1. Build the latest develop package
2. Import the build into a fresh project and import samples
3. Set backend to IL2CPP
4. Add sample scenes to build
5. Set build target to android
6. Perform the build

**Expected behavior**
Build Succeeds

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Unity Version: 2022.2.0f1
 - Plugin Version: Latest Develop

**Additional context**
I think the eos_dependencies.androidlib's project.properties needs the android.useAndroidX flag in it for this to work.

**Comment by arthur740212** [comment]
There is a piece of code that's auto sets androidX to true, seems that it might not be doing its job, will take a look at this.

**Comment by scovertb** [comment]
I've also encountered the sign in error when building with the UPM package, but don't know the cause yet. As far as the R8 error, it can be avoided by enabling the Custom Gradle Properties Template option in the player settings for Android before making the build, since that will generate an up-to-date default properties template. Currently if that's disabled the plugin will copy its own properties template based on the one generated by an older Unity version, which contained the enableR8 property.

**Comment by arthur740212** [comment]
Thanks for the feedback.
The MINIFY_WITH_R_EIGHT variable does become obsolete with Unity 2022.2 and beyond.
[here](https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/844a1d150121af85c0cb81e0122b03762d178b88) is a fix to automate the process such that users wouldn't have to manually enable the custom gradle template properties option anymore.
And [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/1994254228ad1d73778d60535501f8de1e6018b2) is the fix that cleans up the enableR8 setting in the properties file for 2022.2 and above.
Please give it a try and have fun.

**Comment by AndrewKahr** [comment]
Just gave it a try and it looks like it's working. Thank you for the quick fix!
