### ISSUE TITLE
Unable To Log Into EOS on Android

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#205]
**Describe the bug**
When using the account login option on Android, the login fails after attempting to authorize the app with the requested scope permissions. 

**To Reproduce**
1. Build the latest develop into a UPM package
2. Import the UPM package into a fresh project
3. Import the samples
4. Set scripting backend to IL2CPP
5. Add ARM64 to the architectures
6. Set minimum API Level to 6.0
7. Build APK
8. Load APK onto device and open the app
9. Select the Player Data Storage Sample
10. Login via account portal
11. Error should pop up after following the login flow. After confirming the authorization of connecting the application, the confirm button spins for about 10 seconds before the error screen pops up. Feels like a timeout of some kind. 

**Expected behavior**
Login with account portal should allow the user to log in

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 Ultra
 - OS: Android 13
 - Unity Version: 2022.2.0f1
 - Plugin Version: Latest develop

**Additional Context**
This login works on iOS and desktop so I don't think it's an issue of misconfiguring the developer portal, though perhaps something special needs to be done for Android to run that I missed?

**Comment by AndrewKahr** [comment]
Bump not resolved

**Comment by arthur740212** [comment]
We discovered that when there is another app that uses EOS Unity Plugin on the same device, after pressing ALLOW in the Epic permission page, it opens that other app instead of this app we are attempting to login for.
In the case where there is no other app, our target app just doesn't get opened at all, we will take a deeper look.
Side question which might help, does your app also cause warnings from google play protect about the app being untrusted?

**Comment by AndrewKahr** [comment]
I haven't seen any play protect errors.

**Comment by arthur740212** [comment]
Thanks for the response.
According to the login flow from the plugin sample. 
The page is expected to have that timeout-like behavior.
But it should switch back to our app before we see the error on the permission page.
There might be something preventing the return, will keep on investigating.

**Comment by AndrewKahr** [comment]
Bump not resolved

**Comment by arthur740212** [comment]
Hi, thanks for the patience and the attention to our plugin.
We were active on this issue, and the exact cause of this issue is a bit unclear, but we suspect it to be that there is an attribute with two entries and one of them is empty. The two entries do not have a specific order, and it depends on luck which one happens first.
Something even bizarre is that after building under some arbitrary configs, the issue magically disappears for any consequent build of that project, even with previously faulty configs.
Fortunately, we have a fix which will be released very soon, by removing the empty entry from the aar side.
At the moment, a potential hack is to copy our repos's `gradleTemplate.properties` `mainTemplate.gradle` `proguard-user.txt` to the new project's Assets/Plugin/Android/ folder, then build with targeting API Level 29 in the build settings. 
This hack sometimes fixes the issue (4 out of 5 on my unofficial tests), and when it does it fixes it forever.
Feel free to give the hack a shot, if so please let us know if the hack works, would also be curious why and why not the hack works.
Thank you again for the report, willing to hear back soon.

**Comment by AndrewKahr** [comment]
Hey Arthur,
Thanks for the update! 
I haven't yet integrated the plugin into my real project as I've been waiting for the plugin to become more stable so I will probably just wait for the patch you mentioned and test that once it's released. 

API 29 also doesn't help too much even if it works as, to my understanding, Google Play doesn't allow you to upload APKs with a target SDK below 31 right now.

**Comment by arthur740212** [comment]
Since the fix is from external sources, the release might take a little longer than our regular update schedule.
After successfully building with SDK 29, builds with SDK 31 above starts to work too magically. 
This would be an option in case you would like to test the build at the moment.
Thanks for sticking with us.

**Comment by AndrewKahr** [comment]
Ah I didn't realize this project wasn't actually building the aar. 

@arthur740212 could you explain a bit more about what you meant by the attribute with two entries and one of them is empty? I'm wondering if the aar can just be modified as it is just a zip with a different extension.

**Comment by arthur740212** [comment]
There is a `<string name="eos_login_protocol_scheme">eos.yourclientidhere</string>` in certain xml files that must be set for the app to receive login intent. [reference](https://dev.epicgames.com/docs/game-services/platforms/android)

Our plugin has one in `eos_values.xml`, while there seems to also be one in `eos-sdk.aar\res\values\values.xml` which is the empty entry.

**Comment by AndrewKahr** [comment]
@arthur740212 So then should that entry be deleted from the aar?

**Comment by AndrewKahr** [comment]
You're definitely onto something with those entries either not overriding properly or just conflicting. As an experiment I used 7 zip to extract the aar, embedded my client id into res/values/values.xml, rezipped it and renamed zip to aar. Rebuilding the package and using it in an android build did successfully log me in.

Maybe the simple solution is just to unzip and inject the client id into the aar? I believe Microsoft app center for Unity does this and has an implementation for it.

**Comment by AndrewKahr** [comment]
Also on the topic of magically working after changing api versions. I think what might be happening is there's a .gradle folder in your home directory that stores a gradle cache. Perhaps if it does work it just reuses the cached version hence seeming to always work after one successful build?

**Comment by arthur740212** [comment]
According to Epic, the fix would be done in the eos-sdk.aar itself with the 1.16 release, which would spare users from having to unzip/rezip and make changes to the file.
Also thanks for the observation, was guessing something might be stored and reused after a successful build, even though in some cases the result flips between working and non-working.
As for now the only xml related problem is handled, will revisit the cache thing in case something similar happens again.

**Comment by AndrewKahr** [comment]
Awesome, thanks for the update! Any rough idea when that release will happen?

Also on the cache, it is just speculation as I never actually reproduced the behavior you had mentioned about getting a successful build. Just my guess if deleting the library folder was still allowing a functioning build.

**Comment by AndrewKahr** [comment]
Bump

**Comment by AndrewKahr** [comment]
Bump

**Comment by AndrewKahr** [comment]
Bump

**Comment by andrew-hirata-playeveryware** [comment]
Just to update you, I still don't have firm idea when the next EOS SDK update will happen.

**Comment by Lyrcaxis** [comment]
Having the same issue when trying to connect to EOS from inside Unity Editor.
The browser pops up for me to confirm that I indeed want to login, but nothing can be done to pass the 'corrective action'.
![image](https://user-images.githubusercontent.com/32474602/229052080-4ef01797-92cb-4b60-9d4c-bbd62178b4a8.png)

Am I right to assume this is also supposed to be fixed with 1.16 SDK?
And is there anything I can do to make it work immediately?

**Comment by arthur740212** [comment]
@AndrewKahr 
Hello, were you still able to manually modify `value.xml` and rezipping the whole folder back into an aar file?
We were trying this approach for a temp fix, but didn't go well when during gradle build session in Unity.
Were there some preconditions for the zip/unzip to work?

**Comment by AndrewKahr** [comment]
Unfortunately it has been quite a while since I did that. We've ended up just not integrating EOS until this becomes stable.

If I recall though, I was manually unzipping and rezipping using 7 zip (though I don't see why standard zip utilities). Don't recall running into build issues either, I would make sure the zip isn't creating an extra folder layer as that will break the aar (windows by default will do this if you zip up a folder rather than go into the folder, highlight the element, then zip it).

**Comment by arthur740212** [comment]
Huge Thanks! That extra layer in there seems to be the cause of the errors.

**Comment by AndrewKahr** [comment]
Glad I could help! Will this be a fix making it into the plugin or is the wait still on a new version from Epic? Any clue when that might happen?

**Comment by arthur740212** [comment]
Thanks for the help and reports.
1.16 is still on its way, and at the meantime we are reviewing our previous release, focusing on the plugin's "clarity" for the next, that includes making sure the build works with minimal steps for users, and having at least documented guidance for more complicated fixes like this one.

**Comment by lihui2** [comment]
It seems that 1.16 C# SDK has been release, any resoultuion to this problem?
