### ISSUE TITLE
Importing EOS to older Unity version

### ISSUE THREAD

**Issue by G-WASD** [PlayEveryWare/eos_plugin_for_unity#251]
We are using Unity 2019.1.1f1 version for this project and implementation is not working.

We cannot import the project from git or tarball as this unity version did not support these functions at that point (and we cannot upgrade to a newer Unity version because a lot of assets that we used for this project are not supported anymore and updating the Unity version results in them not working anymore).

So what we did we tried to import the EOS (the downloaded version) from the disk, with the package.json from the EOSUnityPlugin_package_template folder. But this gives us nothing (like in the screenshot) and if we hit the "Import in Project" button to get the Samples imported nothing happens.

**1. So how do we import EOS from disk?
2. Also on git, the documentation is referring to Unity -> Tool tab... well this version does not have that also, so how do we configer that, once we import the EOS?**

- _Also please note that we are getting a path error when trying to import manifest.json from the folder Packages saying "Invalid package path [PATH] UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)". Does this mean that this EOS version cannot be imported to this Unity version?_

We ware told we need to have EOS integrated to our game (because of the achievements).

![1](https://user-images.githubusercontent.com/130351727/230864678-eb8f1902-8586-4a14-9ac8-8a52597e24d3.jpg)
![2](https://user-images.githubusercontent.com/130351727/230864691-677bf4a7-4fce-418f-a424-734d20a1d97c.jpg)

**Comment by andrew-hirata-playeveryware** [comment]
Technically yes: we don't support unity versions that far back. We have some code in the plugin that I believe could support at least 2019.4.37f1, but I can't make any guarantees that it still works on latest.

I'm not familiar with that particular Unity error, but I would assume that means the path doesn't actually exist. It could be the case that if someone added the EOS Plugin for Unity UPM to the your project and it was added as an absolute path, or to a path that exists out of your source control, that such an error might occur. That's assuming the error is caused by that. 

One option you should be able to do, is to extract the UPM package in a directory that is under your source control, then add it in UPM via 'Add package from disk' instead of 'Add Package from tarball', [similar to "normal' UPM packages are installed](https://github.com/PlayEveryWare/eos_plugin_for_unity#installing-from-a-tarball). After doing that, you should be able to do edits to the code directly to get it to work in your unity version and otherwise use the work we've done in the plugin. Be mindful that use quite a few binary files, so if you're using github, you'll need to make sure git-lfs is properly configured.

**Comment by G-WASD** [comment]
Thank you for taking the time to investigate this issue. We haven't ruled out the possibility of our own incompetence, but unfortunately, we have made no progress with the following attempts to resolve the problem:

1. Download eos_plugin_for_unity-stable.zip. Copy/pasted the zip to project files (outside of assets this time). Extracting the zip file in a folder in the project. Changed the package.json version to our Unity version.
Imported the package via UPM.
**Result**: The EOS plugin is visible in the UPM but folders (Runtime and Samples) are empty. Also importing samples in the UPM "Import in project" result in the same bug path, printscreen is below (as folders are empty).

2. Downloaded eos_plugin_for_unity-stable.zip. Copy/pasted the zip to project files (outside of assets folder again). Draged the file in the .zip manualy to a folder in the project. Changed the package.json version to our Unity version.
Imported the package via UPM.
**Result**: The EOS plugin is visible in the UPM but folders (Runtime and Samples) are empty. Also "Import in project" result in the same bug path, printscreen is below (as folders are empty)..

3. Downloaded eos_plugin_for_unity-stable.zip directly to the game project. Extracted the zip content directly there (outside of assets folder again). Imported the package via UPM.
**Result**: The EOS plugin is visible in the UPM but folders (Runtime and Samples) are empty. Also "Import in project" result in the same bug path, printscreen is below (as folders are empty)..

**Conclusion**:
We have tried today multiple ways to import the EOS plugin into our Unity project, but it always results in a path error (as shown in the attached screenshot). We have also noticed that both the 'Runtime' and 'Samples' folders are always empty. Even when attempting to import samples from the EOS Plugin for Unity Samples via the 'Import in project' option, we still encounter the same issue (as shown in the screenshot).
All of the mentioned problems are known to us from recent days.

Printscreen 1 (EOS imported via UPM):
![1](https://user-images.githubusercontent.com/130351727/231370382-8ed6ed15-4e5b-4850-a131-4b1a590dffc4.png)

Printscreen 2 (Runtime folder empty):
![2](https://user-images.githubusercontent.com/130351727/231370394-e70c76c3-9f5d-4b1a-80e9-420c40a17692.png)

Printscreen 3 (Samples folder empty):
![3](https://user-images.githubusercontent.com/130351727/231370409-920b61e3-408d-4159-b452-97a5b032b897.png)

Printscreen 4 (Attempting to import Samples via the UPM, results in this bug - as folders are empty):
![4](https://user-images.githubusercontent.com/130351727/231370474-302abec7-5873-433e-9951-cad582885be8.png)

**Comment by andrew-hirata-playeveryware** [comment]
It looks like you're downloading the source for the repository, not the UPM package, based on the name of the file `eos_plugin_for_unity-stable.zip`, which is a zip file, not a UPM package (which are a kind of tar zip file). Downloading the source of the repository won't work because the layout of the repo isn't the same as the layout of the UPM, and due to how github handles git-lfs, it also won't have any of the binaries needed for the plugin to build. I'm sorry for the confusion.

Did you download the latest release from [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/releases), as mentioned in the [install instructions for installing from a tallball](https://github.com/PlayEveryWare/eos_plugin_for_unity#installing-from-a-tarball)?

**Comment by G-WASD** [comment]
We're encountering a new issue now after getting the correct version, integrating and configuring EOS. We're not sure how to tell if a connection has been established and how to trigger the unlocking of an achievement we created in the Dev Portal.

We tried looking into the "Achievements" scene that was provided and imported, but when we tried to start it (by clicking "Play"), the scene failed to load properly, as shown in the attached screenshot. As a result, we're unable to determine how to establish a connection and unlock achievements.

Note that we have already entered the configuration and credentials.

Sample scene, Achievements:
![screenshot_5583](https://user-images.githubusercontent.com/130351727/231698646-f3b899d9-18b8-4319-b20a-67fc8d8a3c25.png)

**Comment by andrew-hirata-playeveryware** [comment]
Have you tried doing a standalone build, with all the scenes from the sample included in the build? Doing that will force you to have to login so you can see if it's working. Then again, if my guess below is correct, then making a standalone build won't work.

Based on the screenshot, it looks like some number of scripts are missing, which I can see based on the Inspector window, and from the console log. If I were to guess the cause, it would be because we're using a UI system, or features of the system, that don't exist in `Unity 2019.1.1.f1`. If that is the case, you won't be able to directly use the sample's UI to test out the features, but instead can just use them as reference. 

On the plus side, you should still be able to use the EOSManager, along with the pre-configured prefab the plugin has, to allow the plugin to work in Unity. Additionally all the sample managers will should also work in your title.

For doing that, I recommend reading the UILoginMenu code, and seeing how to incorporate those kinds of steps that are happening there into your game's existing UI. For doing achievements, checkout the UIAchievementMenu code, which is the script that controlls the Achievement scene.

**Comment by G-WASD** [comment]
Unfortunately, we haven't been able to build the project due to numerous errors that Unity throws up whenever we try to include EOS in it. However, we were able to successfully build it when we removed EOS, so it's clear that the problem lies with EOS.

As we discussed with Unity Support, changing the version numbers without ensuring compatibility with the particular Unity version won't work properly. 
Quote from our chat with the Unity Support staff: **_I understand your concern. Unfortunately, if the integration is not compatible with your Unity version, it may not work as expected and can cause several legacy issues. It might be difficult to resolve these issues later on._**

We've included EOSManager along with the prefabs, but we're still experiencing errors when we reference it directly.

Yesterday, we went through UIAchievementMenu.cs but we're still unable to determine if the connection is even established or not, much less trigger the test achievement that we created in the Dev Portal as non of the samples work.

We acknowledge that Epic has implemented the "if you have achievements on Steam, you must have achievements on Epic as well" rule. However, it appears that they did not take into account the possibility that games may have older versions of Unity. In contrast to Steam's triggers, Epic's triggers are not limited to specific Unity versions. As a result, the tools provided are not designed to function in this manner and a "seamless" integration as, we ware told this would be, is not possible.

We'll be reaching out to Epic Support again to request an exemption on this integration, as it's clear that EOS is not intended for this use.

**Thank you for your continued support and patience, Andrew!**

**Comment by andrew-hirata-playeveryware** [comment]
Just to follow up on this: I'm sorry you've run into so many issues with using the plugin.

I don't have a lot of time to dig in to this issue at the moment, but I was able to get the plugin to login in a very simple
setup in Unity 2019. I imported the plugin via the same method I mentioned above, deleted the x86 binaries (they were causing odd duplicate issues for me),  _did not_ import the samples, added the EOSManager prefab to the scene. I then attached a very simple script to a game object I made in the scene, then logged in via the account portal like so:
```
    void Start()
    {
        Epic.OnlineServices.Auth.LoginOptions loginOptions = new Epic.OnlineServices.Auth.LoginOptions();

        EOSManager.Instance.StartLoginWithLoginTypeAndToken(Epic.OnlineServices.Auth.LoginCredentialType.AccountPortal, null, null, (Epic.OnlineServices.Auth.LoginCallbackInfo loginCallbackInfo) =>
        {
            Debug.LogWarning("maybe we logged in");
        });
    }
```

Of note, when the title is launched by the Epic Game Store, you'll want to use the `Epic.OnlineServices.Auth.LoginCredentialTypeExchangeCode` LoginType, and use the values from the `EOSManager.instance.GetCommandLineArgsFromEpicLauncher` to do the login. 

I hope this is of some help!

**Comment by G-WASD** [comment]
We made again several attempts to get our game to work on the EOS, but unfortunately, we encountered again the same issues. 
So we decided to contacting the ES support team and we requested an exception for our title because we were only able to get EOS to work properly after updating to a supported Unity version. However, this caused several of the assets in the game to become unsupported, rendering it unplayable. 
Fortunately, our request was granted and we were able to launch our game successfully.

Currently, we are working on integrating EOS to two other games that we have, which have Unity versions supported by the EOS. So far, we have not encountered any significant issues during the integration process.

Thank you for your support, Andrew!
