### ISSUE TITLE
Easy Anti Cheat

### ISSUE THREAD

**Issue by Tokey** [PlayEveryWare/eos_plugin_for_unity#28]
Is there any easy way to use EAC with this? I'm aware that it says its not supported, but can I use anticheat with this if I want?

**Comment by adrianpew** [comment]
EAC may or may not work.  Not supported in this case, means we have not tested it with Unity.  The feature does exist in EOS SDK and API to BeginSession and RegisterClient should be available.  You can follow Epic's guide on setting up EAC and determine if it works for you.  Otherwise, we will investigate full support of this feature at a later time.

https://dev.epicgames.com/docs/services/en-US/GameServices/AntiCheat/index.html?sessionInvalidated=true
