### ISSUE TITLE
Move UPM to be in this repository

### ISSUE THREAD

**Issue by FColor04** [PlayEveryWare/eos_plugin_for_unity#298]
I've seen path query parameter used to point to UPM directory (https://github.com/Cysharp/UniTask#install-via-git-url)
It'd be nice to have and you'd have everything in one place

**Comment by andrew-hirata-playeveryware** [comment]
Hello @FColor04,
Historically, we didn't do this because there was some issues / complications with doing this and supporting older versions of Unity. In particular, I seem to recall there being an issue (at the time) with it using a branch that wasn't called `master`. There is also the issue of git-lfs storage space, which can grow quite quickly due to how many very large binaries that this requires to make it work on all platforms. That last issue we have compartmentalized by having it be it's own repo: we can delete old commits or do anything to the history to free up storage issues without affecting our work here on the plugin. That being said, there is a task for this on our backlog, but it's currently fairly low priority compared to other work, such as new platforms, new features, and fixing and working around issues with different versions of Unity.

Thank you for reporting it all the same; even if it's difficult or low priority for us to action on some requests, we appreciate the feedback!
