### ISSUE TITLE
Unable to test the voice feature. Lobby creation is failing

### ISSUE THREAD

**Issue by mechaniqe** [PlayEveryWare/eos_plugin_for_unity#429]
**Describe the bug**
I'm trying to use Voice feature of plugin. Just downloaded v3.0.1 version of plugin and followed installation guide. Opened Lobbies scene. Login with Account Portal works. However, when attempting to create a lobby, I encountered an error message: **"UILobbiesMenu (UIOnLobbyUpdated): LobbyUpdate error 'AccessDenied'."**

**To Reproduce**
1. Go to **Lobbies scene**
2. Click on **Login**, then click on **Create Lobby** (with non-empty bucketId)
3. Scroll down to **Logs**
4. See error: **"UILobbiesMenu (UIOnLobbyUpdated): LobbyUpdate error 'AccessDenied'"**

**Expected behavior**
I expected to create lobby and test voice feature

**Screenshots**
Don't know if it is related with Product settings in developer dashboard. Because when login it says "App is not reviewed/verified
Screenshots:

![Screenshot_63](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/23476584/4c04af63-3aa2-401b-bbb0-be2e8375c3c0)
![Screenshot_65](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/23476584/dcc9d70b-80a1-44e8-af73-825ab493e4a4)
![Screenshot_66](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/23476584/33a58d22-11f7-4fcc-83f0-e287e07329d4)
![Screenshot_67](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/23476584/3dfcede7-2b49-49f8-9f55-46964e5dfdca)

**Desktop (please complete the following information):**
 - OS: [Windows x64]
 - Editor and standalone build
 - Unity Version 2021.3.22f1
 - Plugin Version 3.0.1

**Additional context**
SessionsAndMatchmaking scene works. I am able to create session

**Comment by paulhazen** [comment]
Whenever there is an `AccessDenied` error present in the logs, it actually _is_ indicative that there is something incomplete / unverified in the Developer Portal site. This is (unfortunately) expected behavior for an unverified application.  

It would be nice if unverified applications could make use of all the features, but I suspect there are smart reasons (maybe legal ones?) that they decided not to allow full functionality until an application is verified. 

Once you get your application verified, if you are still experiencing this problem, please do come back and re-open the issue.
