### ISSUE TITLE
EOSTransport causes NGO's StartHost to fail when not initialized.

### ISSUE THREAD

**Issue by Satiriano** [PlayEveryWare/eos_plugin_for_unity#442]
**Describe the bug**
You can't host when you don't have internet connection. This is not the case for other transport layers. (like Facepunch Transport)

**To Reproduce**
1. Be offline
2. (Steam Session Login fails as a result of no internet)
3. Have NetworkManager with EOSTransport
4. Try starting host.
5. See error

**Expected behavior**
You should be able to start host in offline mode, without initialization.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Editor & standalone build
 - Unity Version 2022.3.7f1
 - Plugin Version 3.0.1

**Comment by andrew-hirata-playeveryware** [comment]
Hello @Satiriano !
The Epic Online Services SDK itself doesn't support running in offline mode, therefore we don't support that either. 

When you say it should work "in offline mode without initialization", do you mean you want the plugin to work without initialization the EOS SDK? If that is the case, we can't directly support that because the P2P Interface itself can only be fetched if the EOS platform itself has been initialized. 

If you're able to share it, what's the gameplay / User experience you are trying to achieve? Does the game support LAN style gameplay or a kind of single player mode which you're trying to achieve?

**Comment by Satiriano** [comment]
This is P2P online game, but does support single player too.
Basically, I'm trying to achieve the same thing I had with Facepunch Transport:

The moment you launch the game, you can already run around with your player. To connect to other players, you walk to a specific object in the "home" scene that opens server search menu. The problem with current implementation for my specific use-case, is that there's about a 2 second delay before I can spawn the player - and that's assuming connection to EOS was successful.

It's a specific design where there's no 'main menu' in the beginning. Only escape menu.

I understand that this may be by design, and my use-case is probably rare. I'm trying to find a work-around, but right now I have 2 second delay when spawning player, and if connection to EOS fails, I switch the transport layer to Unity, and spawn the player that way, but that basically means player is in offline mode.

It's hard to explain this in detail, games are complicated heh - and I've tried making this as easy for players as possible.

**Comment by andrew-hirata-playeveryware** [comment]
Hello again!
I do see how that might be difficult; I think some kind of thing where you hide the screen, as you suggested, or defer creating the EOSManager a bit could also be a fix: you'd need to do some re-creation of the objects, but overall, It shouldn't be _too_ bad.

Thanks for using the plugin! As an open source project, it gets better with the more feedback and users we get! Good luck!
