### ISSUE TITLE
Exclude EOS Related files on EOS_DISABLE being set.

### ISSUE THREAD

**Issue by paulhazen** [PlayEveryWare/eos_plugin_for_unity#466]
For projects where EOS_DISABLE is set, it would be nice if the EOS-related files be excluded, instead of the plugin simply not loading them.

**Comment by paulhazen** [comment]
Marking as unresolved and closing - issue does not actively cause any problems and will likely be resolved in future iterations of the build pipeline.

**Comment by Jamez0r** [comment]
> Marking as unresolved and closing - issue does not actively cause any problems and will likely be resolved in future iterations of the build pipeline.

Hi Paul - what would be the best way for me to keep an eye out for this being fixed in a future release? Would checking this changelog be the best way? https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/blob/master/CHANGELOG.md

The original reason I was requesting this change is that the porting team I am working with said that when building the game for (certain?) consoles, the resulting build file is a package that they can't go into afterward to strip out those unnecessary files. I am not sure exactly what they had to do on their end but they seemed to have had to completely strip out the EOS Plugin on their branch of the project in the repo.

Thanks!
