### ISSUE TITLE
Android & iOS

### ISSUE THREAD

**Issue by MenesApps** [PlayEveryWare/eos_plugin_for_unity#47]
Hi,
I am hoping to move to EOS since Gamesparks is closing and it seems the best alternative, but my games are for mobile and it doesn't seem to be supported by this plugin for now. 
Any idea when it will be? 
Thanks :)

**Comment by kenofori** [comment]
Same Here, Waiting for EOS Unity SDK for iOS + Android to be available

**Comment by FakeByte** [comment]
> Hi, I am hoping to move to EOS since Gamesparks is closing and it seems the best alternative, but my games are for mobile and it doesn't seem to be supported by this plugin for now. Any idea when it will be? Thanks :)

You could use the eos c# sdk for mobile while the unity plugin doesnt support it yet

**Comment by andrew-hirata-playeveryware** [comment]
It's been a while since I've looked into it, but there is some basic work that was done to get it working on Android. It's technically 'available' now, but it's not guaranteed to be working 100%. iOS is further behind, but is partially working on another branch that hasn't been pushed. I can't give any specific release dates at this time though.

**Comment by domlaurenti** [comment]
Apologies but we can't be specific about release dates at this time, we can only say that the plugin currently officially supports PC only. 
I'd keep an eye on the roadmap here for specific support items and release dates: https://trello.com/b/rLvzFJfE/eos-public-roadmap
