### ISSUE TITLE
I am using this library and authenticating login with Steam Session, but token expires.

### ISSUE THREAD

**Issue by nitrocss** [PlayEveryWare/eos_plugin_for_unity#484]
Hey, I can't find any information on how to properly extend token before it expires. It seems after a certain amount of time you get logged out of EOS.

Please help me :)

**Comment by Jason-PEW** [comment]
Hello, 

Thank you for reaching out. While we work on getting this added to the plugin properly, let me give you a walkthrough on how to set this up yourself. 

When you successfully log in using `StartConnectLoginWithSteamSessionTicket()` or `CreateConnectUserWithContinuanceToken()`, you'll want to call `ConnectInterface.AddNotifyAuthExpiration()`. In the OnAuthExpirationCallback you'll want to call `StartConnectLoginWithSteamSessionTicket()` again.

The AuthExpiration event will happen when reauthentication needs to happen, and calling the connect login function again will handle that reauthentication for you. 

An example of this can be found in EOSManager.cs line 1250 `ConfigureConnectExpirationCallback()` 

Please let me know if this helps or if I can provide further assistance.

**Comment by Satiriano** [comment]
Hey, thanks for getting back to me. I'll test this out and get back to you.

**Comment by paulhazen** [comment]
Hi @Satiriano, did this end up working for you? I'm going to mark this issue as closed, but mark it as `unresolved` because it's not something that we actually have an in-place solution or example for, and I want to keep track of it so we can add that in the future. Please feel free to re-open if your issue is persisting, or if you feel there is something broken about the implementation.
