### ISSUE TITLE
EOS API Config get saved in streaming assets folder!!!

### ISSUE THREAD

**Issue by CK85** [PlayEveryWare/eos_plugin_for_unity#49]
Hi,

just want to let you know that your eos plugin saves the api keys config as a readable json file in the streaming assets folder, everyone can read that in any standalone build! You should move it to a resources folder at least (and make a scriptable object or something similar.)

Best regards,
Chris

**Comment by andrew-hirata-playeveryware** [comment]
This is by design. The configuration file needs to be read before the Unity runtime environment is fully setup and running from a native DLL, which means that none of the usually Unity niceties for obscuring config files work. There is a partially implemented feature that lets the native code load another DLL, and call functions from it to load values, but that is just differently insecure, though more obscured. The native DLL could potentially be changed such that the DLL it reads from would have to be signed, which would provide more security, assuming such a thing could work.  Of course, that brings with it more work on users of the plugin to get certs and to sign DLLs.

It is a problem I'd like to solve, and I'm open to solutions, but I haven't had the time lately to craft a good one.

**Comment by TheSLAP** [comment]
Is this being fixed? Client Id, secret, and encryption key are all exposed neatly in a readable JSON.

**Comment by KesKim** [comment]
@andrew-hirata-playeveryware Maybe the config JSON could be stored in a path that does not get included to builds by default, and then use a PostProcessBuild script to copy it into the build folder if some EOS_ENABLED or other compiler define is set? While in Editor, you could have a compiler #if #endif block load the config from the Editor path and in builds you'd get it from the StreamingAssets.

At least this would prevent the config from getting included in ALL builds of one game (for multiple platforms, etc.), not sure how to solve the file being readable in builds where EOS is supposed to be used.

**Comment by MerriemWeebster** [comment]
I think there should still be an option for obfuscation to at least add a slight layer of difficulty in getting the client secret of the game.
