### ISSUE TITLE
Voice support

### ISSUE THREAD

**Issue by flyingaudio** [PlayEveryWare/eos_plugin_for_unity#50]
Is voice currently supported with this plug-in?  The following link from Epic states that it is:
https://dev.epicgames.com/en-US/news/epic-online-services-releases-plugins-for-unity-and-unreal-engine

but the support features listed with this git says it is not supported.
If it is not supported, when is it anticipated?
Thanks

**Comment by andrew-hirata-playeveryware** [comment]
The base native code plugin as released _should_ have support for loading the xaudio DLL and configuring the plugin correctly so that voice chat can function. That being said, there are no completed samples nor helper methods implemented for show how to use voice chat, and how to create the voice chat lobbies. Unfortunately I don't have any updates at this time on when that work will get finished.

**Comment by andrew-hirata-playeveryware** [comment]
Hello again @flyingaudio! Sorry for the long lapse in time before providing an update. Version 1.0.4 is soon to be released and will contain more complete samples with of how to hook up voice chat in lobbies. As mentioned before, the current version of the plugin also has all the lower-level things configured to allow for voice chat to work.

**Comment by andrew-hirata-playeveryware** [comment]
Just in case you did see, version 1.0.4 is out! It should have samples on using voice chat included!
https://github.com/PlayEveryWare/eos_plugin_for_unity/releases/tag/v1.0.4
