### ISSUE TITLE
Editor hangs when playing more than one time

### ISSUE THREAD

**Issue by nospoone** [PlayEveryWare/eos_plugin_for_unity#523]
**Describe the bug**
Hello! It seems that I can't play the game more than once in the editor. The editor will simply hang on subsequent plays, with either the indeterminate progress bar (_Hold on..._) or without any indications whatsoever.

**To Reproduce**
I've attached a [minimal reproduction case](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/14043012/eos-hang.zip), without my config:
- Open project
- Fill _dev portal configuration_ (although invalid config will _also_ trigger this)
- Open `Scenes/SampleScene.unity`
- Hit Play in the editor;
- Check console for `initResult = Success`;
- Stop, and hit Play again in the editor;
- Unity should be either stuck without a progress dialog, or showing the _Hold on_ dialog with the indeterminate progress bar;

**Expected behavior**
Being able to hit Play more than once 😁

**Desktop:**
 - OS: Windows 11 x64
 - Editor only (works correctly in builds)
 - 2022.3 (tried a couple of minor versions, the repro case uses 2022.3.11)
 - 3.0.3, installed from the tarball (but using git also reproduces the issue)

**Additional context**
The plugin reports that it connects correctly the first time. While it doesn't show anything in the console for the subsequent times (since the editor never switches to actually playing,) the last line of `Editor.log` shows `initResult = AlreadyConfigured`.

For now, I'll install the package locally and try to step through `Init` to see what's going on, but still wanted to report in case I'm just doing something dumb!

**Comment by nospoone** [comment]
Here's my finding from spending a little bit of time on this:
It seems that execution stops [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/Assets/Plugins/Source/Core/SystemDynamicLibrary.cs#L164)... I haven't worked with any of the Win32 APIs or even C in a long time, but it seems that `FreeLibrary` is somehow (as per Rider's debugger) never returning—which I'm not even sure how that works.

I ran out of time to dig further, unfortunately!

**Comment by paulhazen** [comment]
Okay - I got to the bottom of it. The issue was that the plugin was not completely set up to function properly in your project. Specifically, the following steps do not appear to have been taken in your minimal example `eos-hang`:

<img width="787" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/6595db09-bf97-4572-9fd3-8620316bcb5c">

The full document on configuring the plugin can be seen [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/configure_plugin.md).

Once I followed those steps, I was able to play, pause, play, pause to my heart's content :)

If, after following those steps, you're still running into issues, please feel free to re-open this issue. Having your minimal example was super helpful, thank you for that. If you have another issue, providing something like that again would definitely be awesome.

**Comment by nospoone** [comment]
Adding the prefab indeed fixes my issue! Thanks for taking the time to look into it, and sorry it was something as simple as _not reading the instructions_.

> in case I'm just doing something dumb!

It was indeed the case ☝️

> Having your minimal example was super helpful, thank you for that.

Least I could do!

**Comment by paulhazen** [comment]
> Adding the prefab indeed fixes my issue! Thanks for taking the time to look into it, and sorry it was something as simple as _not reading the instructions_.
> 
> > in case I'm just doing something dumb!
> 
> It was indeed the case ☝️

haha no problem. I tend to be of the opinion if instructions are not being read, they can probably be written better, so this helps us improve things :)
