### ISSUE TITLE
Keychain access request on Mac

### ISSUE THREAD

**Issue by mechaniqe** [PlayEveryWare/eos_plugin_for_unity#536]
Hello,

The app tries to access keychain on OSX platform saying `X wants to access key "com.epicgames.sdk.auth.access_token" in your keychain` and `X wants to use your confidential information stored in "com.epicgames.sdk.auth.access_token" in your keychain` (which isn't very nice), seemingly when it tries to relogin on app start.

I tried to manually prevent that from happening (e.g. use persistentDataPath for save/load), but seems like it's happening somewhere inside of PlatformInterface.

Is there a way to direct EOS not to use keychain on Mac?

EOS 3.0.3 plugin version
Unity 2021.3.22f1

**Comment by arthur740212** [comment]
Persistent login reads the access token to login to the previous logged in account, and that information is stored in `com.epicgames.sdk.auth.access_token` in the keychain, and that is the only thing stored there.

Are you worried about security or is the login prompt causing trouble?

**Comment by arthur740212** [comment]
We will investigate if this is possible.
Will keep this issue open for the time being.

**Comment by arthur740212** [comment]
After checking written descriptions in LoginCredentialTypes.cs,
`On Desktop and Mobile platforms, the persistent refresh token is automatically managed by the SDK that stores it in the keychain of the currently logged in user of the local device.`
It is unlikely to bypass that part without directly modifying the SDK libs.

At the same time, using the keychain to store confidential information is generally good practice on MacOS according to https://support.apple.com/guide/mac-help/use-keychains-to-store-passwords-mchlf375f392/mac

What it essentially does is link the info with an account instead of a device.
If a device is stolen, the account could be logged out remotely, while the info on the device would be beyond control.
