### ISSUE TITLE
Please support Ecommerce for MacOS

### ISSUE THREAD

**Issue by BestStream** [PlayEveryWare/eos_plugin_for_unity#616]

**Comment by andrew-hirata-playeveryware** [comment]
Hello @BestStream,
We currently don't support E-Commerce APIs on macOS because Epic doesn't support them. I'll work with the team to clarify the reason it isn't supported.

**Comment by andrew-hirata-playeveryware** [comment]
Created a task internally to update docs, and closing this ticket

**Comment by BestStream** [comment]
@andrew-hirata-playeveryware I understand that there is a reason why the overlay does not work in macOS. But I observed the following: we made a login - on Windows it works through the overlay, on macOS it opens in the browser and it works. So my question is, perhaps if you make the Ecom through the browser rather than through the overlay, it might work?

**Comment by andrew-hirata-playeveryware** [comment]
Yes, but the Ecom checkout method fails / won't work without the overlay, hence why we don't have support for it.

The method you're describing would work, except that Epic controls how works, so we wouldn't be able to make that happen without Epic directly providing it. Hence why we don't support it.

That all being said, I think something _kind of_ similar to what you're described could be done, but it might have to be done differently for each title, and our team currently doesn't have the bandwidth to tackle it at this exact moment.

The potential work-around would go something like this:
1. User opens up the store / place to buy things in the title
2. User gets booted to a web page to make a purchase
3. User makes a purchase
4. User has to close browser page
5. User has to go back to the app
6. Title has to infer a purchase took place
7. Title has to reload / sync values without being informed what actually changed.
8. If an issue occurs, the title has no way to give feedback to the user
9. If the user cancels the purchase _or_ decides to go to a different page on the browser and buy a different item, the title needs to handle that too.

Not the best user experience, but it could be done.

As far as pseudo-code goes, your title would need to do something like this: 
* Make a call to `EComInterface.QueryEntitlementsOptions` to check what is currently purchased
* Ensure your in game store has the correct things shown based on that call.
* Generate URLs for each item in your in game store 
    * They kind of look like they're all of the form `https://store.epicgames.com/en-US/p/your-title-name--catalog-item-name`
    * However, this isn't documented anywhere, so It might change. Additionally, if you change something with your title or catalog item's name, it also might change. It could also _not_ change, which means your title would need to handle that situation as well.
* Configure each UI item so that when interacted with it opens the generated URL in the browser:
    * `Application.OpenURL` should work
* When the title gets focus again, call `EComInterface.QueryEntitlementsOptions` again to check what's changed and what needs to be redeemed. 

If you do find a working solution, the team and I would appreciate any code you're willing to share.

**Comment by BestStream** [comment]
@andrew-hirata-playeveryware
Thank you very much for your advice! This does look like an acceptable temporary solution.

It's really surprising that the Epic team shouts that they made services that work on all platforms, but it turns out to be wrong.

Thank you and your team for your great work and support!

**Comment by andrew-hirata-playeveryware** [comment]
Hey again @BestStream,

I won't be able to work on this for maybe a month or two, _but_ I think there exists a chance that we could make a version of this using information from [this Epic doc](https://dev.epicgames.com/docs/epic-games-store/protocol-activation), along with something similar to how I explained above. It would probably be added to the plugin as a sample to allow you and other users to modify it if needed. In the mean time, hopefully that extra documentation is helpful for you as well.
