### ISSUE TITLE
GC Alloc > 0B

### ISSUE THREAD

**Issue by tamtahirli** [PlayEveryWare/eos_plugin_for_unity#635]
There is Garbage being allocated in the NetworkLoop caused by P2PInterface.GetNextReceivedPacketSize
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/70985764/c70dab7e-742e-4ad8-a169-6b3831041f3f)

**Comment by andrew-hirata-playeveryware** [comment]
Hello @tamtahirli,

I don't understand what issue you're encountering?

**Comment by tamtahirli** [comment]
> Hello @tamtahirli,
> 
> I don't understand what issue you're encountering?

Hi @andrew-hirata-playeveryware, the P2PInterface of the EOS SDK is generating garbage which is slowing down CPU time in both editor and build.

It is happening in: public Result GetNextReceivedPacketSize

Stack trace leads to:
internal struct GetNextReceivedPacketSizeOptionsInternal : ISettable<GetNextReceivedPacketSizeOptions>, System.IDisposable
Specifically, this method:
public byte? RequestedChannel
{
	set
	{
		Helper.Set(value, ref m_RequestedChannel);
	}
}
It will generate garbage, and it shows that it is boxing the nullable byte. Profiler shows this:
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/70985764/5a9e9e05-0053-49be-96d6-a20eb693c73a)


OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM] Windows x64
Editor, or standalone build Both (android build as well)
Unity Version 2021.3.30f1
Plugin Version 3.1.3

**Comment by andrew-hirata-playeveryware** [comment]
Yes that's due to how the EOS SDK itself marshals values across. It's pretty difficult to make a call into native code without some amount of allocations given the structs that need to be passed around, and the need to ensure that the value sticks around and doesn't get collected.  

As a quick test, are you able to do a modification to the set method in `SetHelper.Set<T>(T? from, ref IntPtr to) where T : struct` ? You could try and see if changing it to only call AddAllocation if the byte has value helps.

**Comment by tamtahirli** [comment]
@andrew-hirata-playeveryware 

It is actually also wherever the value is returned, allocated or not. It seems the problem is it being a Nullable<byte> (byte?) to begin with but I'm not an expert. Do you have an example project you can test to reproduce and investigate the issue?

I tried your suggestion nonetheless and it still produced garbage because it was passing around the nullable byte.

I think the byte? is not null, but the nullable type of byte is creating garbage no matter how you use it.

Here is an image of the profiler expanded more, it creates garbage wherever the byte? is returned:
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/70985764/bf758b6d-be3f-49b2-a4dc-1ec12f734b32)

**Comment by andrew-hirata-playeveryware** [comment]
To clarify some terminology: 
* Only the managed (C#) code creates "garbage", if we mean garbage to be "Allocations which the Garbage Collector (GC) collects.
* The EOS SDK can be split into two parts: Native code (C) and the C# wrapper (Which is what you're looking at here).
* Other kinds of allocations are just that: memory allocations. The garbage collector won't collect them. These can come from both native code and the C# wrapper via it's various 'Helper' classes.

Allocations in the native code don't show up in the Unity memory profiler, as far as I know. So you shouldn't see those there.

The .*Internal structs are the C# equivalents to the native code structs. They don't follow Managed code conventions (i.e. alignment and pointer types), and they mostly exist to make it easy to do the interop with native code. Generally speaking they _may_ indirectly cause allocations because data gets copied into them, or their IntPtrs point to data that gets allocated and has data pointed to it.

Back to the issue at hand; in order to pass that struct off to native code _some_ kind of memory needs to be used. The current code appears to always allocate at least one Nullable byte, which in C# is kind of "object" (object in the generic sense, not the C# sense) and is one of the things showing up. The code could be _slightly_ improved by making it so that it doesn't allocate the byte if the passed in Nullable byte is indeed null. Hence my suggesting to do that quick code change to see if that helps.

More generally, I think the code wrapper code needs to be improved to handle these situations a little bit more memory friendly, which is more of an Epic task than a task for our Plugin.

Concerning samples, we do have some in the plugin that can be used for testing and as examples to users implementing our plugin, but as a team we don't currently have the bandwidth to look into this. If you find anything on the plugin side of code that you think could help with this though, I'd gladly look at a PR to see if we can't get integrated into our `development` branch.

**Comment by tamtahirli** [comment]
After some time, I did manage to reduce it to 80 bytes by not passing a channel into GetNextReceivedPacketSize. Seems anytime I add a channel it creates garbage which is quite unfortunate

**Comment by paulhazen** [comment]
Hi @tamtahirli I'm glad you were able to reduce to 80 bytes, but I agree it is unfortunate. I'm going to mark this issue as both "unresolved" and "wontfix" for the time being, so that when we have more bandwidth we can circle back to it.

As @andrew-hirata-playeveryware rightly points out, this issue is primarily in the territory of the EOS SDK - the implementation of which we cannot change. However, we do reach out to Epic from time to time to provide feedback on issues that our users discover - and we will be certain to pass this one on to Epic next time we have that conversation.
