### ISSUE TITLE
EOSManager_EOSGetters.cs:72 - here a annoying error constantly appears, although this is not the error

### ISSUE THREAD

**Issue by BestStream** [PlayEveryWare/eos_plugin_for_unity#649]

**Comment by paulhazen** [comment]
Hi @BestStream - I'm not seeing the error on my end - although I don't doubt you are experiencing it. Can you give a little more detail (for instance, can you post when the error is?)

**Comment by BestStream** [comment]
@paulhazen I'm referencing this code, so it seems obvious when the error occurs - when I use GetEOSEcomInterface in the Editor
```
            public Epic.OnlineServices.Ecom.EcomInterface GetEOSEcomInterface()
            {
#if UNITY_EDITOR
                UnityEngine.Debug.LogError("Attempting to grab the EComInterface in the Editor: Won't work because the overlay isn't supported in the Unity Editor");
#endif

                return GetEOSPlatformInterface()?.GetEcomInterface();
            }
```

**Comment by paulhazen** [comment]
Apologies for my continued lack of understanding. Let me see if I can be more precise.

It _is_ true that if you are trying to get the interface for the ECommerce component of the EOS SDK from within the editor you will and _should_ get an error telling you that because the plugin is running within the editor, it cannot interact with the overlay - which is the only context in which the ECommerce component should be utilized.

You say that this error constantly appears, but that this is _not_ the error. What exactly do you mean by it _not_ being the error?

Are you using one of the sample scenes, or are you encountering this problem in your own implementation? Either way, can you tell me what input interaction precipitates the error being triggered?

Much thanks for your patience while I try and help you track this down.

**Comment by paulhazen** [comment]
> _No description provided._

As a matter of good practice - I endeavor to respond accommodatingly to issues filed regardless of adherence or lack thereof to norms - but it may serve both of us well moving forward if you are able to fill out the description of the issue you are experiencing and provide a little more context from the beginning. Just a gentle suggestion that might help us more quickly arrive at a solution for you when a problem arises.

**Comment by BestStream** [comment]
@paulhazen The overlay doesn't work, that's true. But it is not true that the overlay is the only thing in Ecom interface. Both Offers and Entitlements work in the Editor. I implemented the entire purchasing experience in the Editor and MacOS (have to open the browser instead of the overlay, but this is ok enough).

**Comment by paulhazen** [comment]
Closing this issue as it has been resolved in `development`, and will be included in our upcoming release.
