### ISSUE TITLE
Fail to find the right way to set identifiers

### ISSUE THREAD

**Issue by BestStream** [PlayEveryWare/eos_plugin_for_unity#656]
There are 3 environments (Dev, Stage, Live) for each of which there are 2 identifiers (SANDBOX, DEPLOYMENT). So when I create the test version I have to specify the identifiers for Dev, and in the release version I have to specify the identifiers for Live. The plugin prompts you to specify only one pair. What is the recommended solution to this? So as not to change manually every time. There probably should be some way to create 3 configs and switching between them, but I didn’t find docs on this issue

**Comment by paulhazen** [comment]
The way that this is supported is via `Tools -> EOS Plugin -> EOS Configuration` under the 'Main' section header, there is a section where you can add overrides. 

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/d5d7b8d6-e17e-4ae1-93a6-cd931e1ed9ca)

In order to indicate the override you want to use; you need to copy and paste the value from the list into the fields above this section in that window. We do document this process [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/epic_game_store.md#overriding-sandbox-andor-deployment-id) in our documentation - but I believe it could be made clearer in the documentation and be more intuitive in the user interface. We will consider adding a task to our list to better support this scenario. 

In the meantime, between the screenshot above and the documentation that is linked you shouldn't have any trouble accomplishing what you want.

**Comment by BestStream** [comment]
@paulhazen Thank you, now it’s clear where to enter additional identifiers. However, I didn't understand how to switch them. I see the documentation mentions "the sandbox ID can be overridden with the launch argument", but what does the launch argument mean? Can you provide an example? Usually in most other plugins IDs are specified during initialization, so it seems that this should be set here EOSManager.Instance.Init()

**Comment by paulhazen** [comment]
@BestStream The documentation mentioning the launch argument pertains to launching to the application from the command line - as far as I understand your scenario it does not apply.

It seems like we could stand to do some work on the documentation around this feature - I'll make a note for us to do that in an upcoming release.

**Comment by paulhazen** [comment]
> However, I didn't understand how to switch them. 

Unfortunately, the overrides list is more like a list that you can copy and paste from. Our User Interface could use some improvement in this area. So when you want to switch you'll need to copy and paste them into the non-override value entry on that same window. Regardless of that not being the best implementation; does that make sense to you?

**Comment by BestStream** [comment]
@paulhazen It looks like there is no convenient way to do this yet. If you ask me how it would be convenient to use - user should be able to create several config files so that there is a config for each environment and so that in Init user can specify the index of the environment that needs to be used.

**Comment by paulhazen** [comment]
> @paulhazen It looks like there is no convenient way to do this yet. If you ask me how it would be convenient to use - user should be able to create several config files so that there is a config for each environment and so that in Init user can specify the index of the environment that needs to be used.

I agree that our story around this feature could be a better one. I've added it to our tasking for us to discuss how to approach this in a better way. Since this is no longer an "issue," but more accurately a feature request, I'm going to mark this issue as "unresolved," (which we use for issues like this) and close the issue.
