### ISSUE TITLE
Add a checkmark to config to disable EOSBootstrapper.exe installation

### ISSUE THREAD

**Issue by PetrBodnar** [PlayEveryWare/eos_plugin_for_unity#679]
We are using only Easy Anti Cheat feature.
We do not need EOSBoostrapper and all related stuff (see discussion https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions/654)
We need a way to disable EOSBootstrapper.exe installation through Unity Editor (without modifying sources of plugin).

**Describe the solution you'd like**
It would be cool if Eos Plugin Configuration window will have a "Install EOSBootstrapper" checkmark

**Comment by WispyMouse** [comment]
Ahoy @PetrBodnar! Thank you for the suggestion. PlayEveryWare's engineers are going to assess the feasibility of this task, and will get back to you after we've researched this.

**Comment by WispyMouse** [comment]
Ahoy @PetrBodnar ! This has been merged over in to the plugin and is available for you to use.

The final form of this is to use platform flags, rather than a checkbox. Inside the EOS Configuration popup window, there's a field to specify "Platform Flags". By adding "DisableOverlay" to your list of flags here, or as your only flag, then the plugin does a couple of things. The first is that the EOSBootstrapper.exe will not be included in your build, which is what you were requesting in the first place. The second is a feature that was already silently present, where having this flag specified will avoid ever initializing the overlay.

The information on configuring this is now in our [Frequently Asked Questions](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/development/docs/frequently_asked_questions.md#how-do-i-disable-the-overlay) page. The feature is present in the `development` branch, and will make its way to a release in the near future.

Thank you for your request!
