### ISSUE TITLE
git-lfs command not found, how to fix?

### ISSUE THREAD

**Issue by PixelSir** [PlayEveryWare/eos_plugin_for_unity#70]
I keep getting this error when I try to import the project:

    Error when executing git command. git-lfs filter-process: git-lfs: command not found
    fatal: the remote end hung up unexpectedly

I read the unity documentation for this but I have no idea what I am suppose to do to get the package manager to actually work for this.

A step by step guide would be helpful because unity is terrible with documentation on explaining this.

**Comment by pew-dahs** [comment]
From your error message, you need to install git-lfs as we use this for storing larger files in the repo. You can get it from here [https://git-lfs.github.com/](https://git-lfs.github.com/) and it has additional information about it.

**Comment by PixelSir** [comment]
This is what confused me though, for my git repository for the project I do have LFS enabled already - my asset files show they are using LFS on the GitHub website when I looked.

![image](https://user-images.githubusercontent.com/33559521/175439501-f4465baa-a8e6-482f-9b9f-3690ace8be7b.png)


So I have it installed for my unity project, I am 100% sure of that. But I am unsure if that error relates specifically to my GitHub repository or some thing to do with package manager settings, or do I need to include some specific file formats in the GitHub file for it to work for the EOS plugin ?

**Comment by pew-dahs** [comment]
There's also the command `git lfs install` that you need to run in your git repo if you haven't done that. However, if you're still having problems, you can also import the project using the tarball instead as this will have everything. Otherwise, you can check out the forums and documentation on the git-lfs page for additional help as this issue is related to setting up git-lfs in a git repository.
