### ISSUE TITLE
3.2.0 - wrong placeholders in PlatformSpecificAssets/EOS/[Windows|Mac|Linux]/EasyAntiCheat/Settings.json

### ISSUE THREAD

**Issue by PetrBodnar** [PlayEveryWare/eos_plugin_for_unity#701]
**Describe the bug**
In plugin version 3.2.0 `PlatformSpecificAssets/EOS/[Windows|Mac|Linux]/EasyAntiCheat/Settings.json` contains wrong placeholders
Should be
```	"title"											: "<ProductName>",
	"executable"									: "<ExeName>",
	"productid"										: "<ProductID>",
	"sandboxid"										: "<SandboxID>",
	"deploymentid"									: "<DeploymentID>",
```
But in fact:
```	"title"											: "Example Game",
	"executable"									: "<gamebinary.exe>",
	"productid"										: "<your_eos_productid>",
	"sandboxid"										: "<your_eos_sandboxid>",
	"deploymentid"									: "<your_eos_deploymentid>",
```
And code in
`PlayEveryWare.EpicOnlineServices.Build.EACUtility.ReplaceFileContentVars`
cannot find and properly replace them durng build

 - Plugin Version 3.2.0

**Comment by WispyMouse** [comment]
Ahoy @PetrBodnar! Our team has fixing this as a high priority sprint task, and is going through code review now.

Currently this `Settings.json` file is regenerated every time you build. The current work around would be to make those replacements yourself, which I admit is pretty tedious! Our team will fix this set of strings as soon as possible so that builds will be generated with the appropriate `Settings.json` for EasyAntiCheat.

**Comment by WispyMouse** [comment]
This has been merged in to the `development` branch. Thank you for filing this issue!
