### ISSUE TITLE
Bug with "Session" class wrapper from PlayEveryWare, variable "NumConnections" stuck at 1 no matter how many players join

### ISSUE THREAD

**Issue by superrafyYT** [PlayEveryWare/eos_plugin_for_unity#741]
**Describe the bug**
When a player creates a session, and another players joins, the third joining still see the "NumConnections" still at 1 instead of 2

**To Reproduce**
1. Create a session
2. Join a session with 2 clients
3. Find session with a 3rd client
4. 3rd client sees the session with apparently just 1 connection/player

**Expected behavior**
I guess it should show 2 in this example rather than 1

**Desktop (please complete the following information):**
 - OS: Windows x64(editor)
 - Editor, or standalone build
 - Unity Version: 2022.3.26f1
 - Plugin version: 3.0.3 (November 2023)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23
 - OS: android 14
 - Unity Version: 2022.3.26f1
 - Plugin version: 3.0.3 (November 2023)

All clients use these login type:
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/86516779/22b19016-1f38-43ca-9f16-3615f8af8335)

**Comment by WispyMouse** [comment]
Ahoy @superrafyYT! Thank you for creating this issue.

We investigated the Sessions sample, where this is primarily used, and found some things about the C sample it was based off of for the Epic Online Services SDK. While the C# sample in this repository mostly has parity with the SDK's C sample, it is clear that there are flaws in the maintenance of the Session's information. For example, there isn't currently a mechanism for updating members of the Session with information about how many people are in the Session, or when certain parameters change. This results in everyone's client thinking there's only one member of the session, which is definitely not always true!

Our team is going to look in to how to improve this experience and the Sessions object. It's an objective of ours to find a solution for maintaining this NumConnections number properly, as well as other elements of the Session. We'll get back to you after we've made the appropriate changes.

**Comment by superrafyYT** [comment]
alright, thanks!

**Comment by WispyMouse** [comment]
Ahoy! I wanted to update you on this.

The Sessions Interface does not implement any way to inform members of the session that someone has joined or left, if they hadn't joined through the social interface. Our team is currently working on a rework of the Sessions sample that would include Peer 2 Peer messaging. The goal is to create a sessions sample that implements a message upon a user joining, leaving, or the session being modified, that would key everyone to update their session's information.

We'll keep you updated on when this makes its way in to a place you can pull from!

**Comment by WispyMouse** [comment]
Hey @superrafyYT ! I wanted to let you know where this is at. It's been a little bit, and we wanted to show you that things are in the works.

We've added things to the Sessions sample that leverages Peer 2 Peer messaging. Nothing about the Sessions *Interface* has changed, and nothing about the *EOS SDK* has changed. The only thing changing is that our Sessions sample will now demonstrate how to implement a Peer 2 Peer messaging system in order to reflect changes.

Whenever an appropriate action happens, the peer will inform the host of a change, and the host will inform all peers of the changes. If someone were to utilize the samples example, they could reflect these adjustments, and their Sessions would locally be updated appropriately.

The pull request for that is pull request #827 . It has been merged into `development`. The next time we have a release, the sample will be available. Otherwise you could look at the `development` branch for solutions.

**Comment by superrafyYT** [comment]
@WispyMouse thank you for adding it, i'll check it out :)

**Comment by WispyMouse** [comment]
Ahoy @superrafyYT ! This has been merged into stable! Lemme know if you have any further need for examples; re-open this issue if you would like more! Thank you for the suggestion and pointing out this flaw.
