### ISSUE TITLE
Cannot log in on AuthFriends Scene

### ISSUE THREAD

**Issue by LightfootBros** [PlayEveryWare/eos_plugin_for_unity#755]
So I have followed this video and set everything up, but I still cannot get the AuthAndFriends scene to log in.  Iget these errors when the scene runs.

```
Exception: Epic Online Services didn't init correctly: InvalidParameters
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Library/PackageCache/com.playeveryware.eos@4769421d62f6/Runtime/Core/EOSManager.cs:682)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Library/PackageCache/com.playeveryware.eos@4769421d62f6/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Samples/Epic Online Services Plugin for Unity/3.2.1/Standard Pack _ EOS Plugin for Unity Samples/Scripts/Core/EOSHostManager.cs:49)

```
```
NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.Samples.EOSFriendsManager..ctor () (at Assets/Samples/Epic Online Services Plugin for Unity/3.2.1/Standard Pack _ EOS Plugin for Unity Samples/Scripts/EOSFriendsManager.cs:110)
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <80e08c2cc04049bf931fc9038d04f397>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <80e08c2cc04049bf931fc9038d04f397>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) (at <80e08c2cc04049bf931fc9038d04f397>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) (at <80e08c2cc04049bf931fc9038d04f397>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) (at <80e08c2cc04049bf931fc9038d04f397>:0)
System.Activator.CreateInstance[T] () (at <80e08c2cc04049bf931fc9038d04f397>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.GetOrCreateManager[T] () (at Library/PackageCache/com.playeveryware.eos@4769421d62f6/Runtime/Core/EOSManager.cs:368)
PlayEveryWare.EpicOnlineServices.Samples.UIFriendsMenu.Start () (at Assets/Samples/Epic Online Services Plugin for Unity/3.2.1/Standard Pack _ EOS Plugin for Unity Samples/Scripts/UI/Friends/UIFriendsMenu.cs:92)
```

```
NotConfiguredClientException: Unity VCS client is not correctly configured for the current user: Client config file C:\Users\james\AppData\Local\plastic4\client.conf not found. Please execute 'cm configure' to perform a text mode configuration or 'plastic --configure' for graphical mode.
Codice.Client.Common.ClientConfig.get_SafeData () (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Codice.Client.Common.ClientConfig.IsSymlinkSupportEnabledOnWindows () (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Codice.Client.Common.Platform.GetPath (System.String path, System.Boolean preserveName, System.Boolean solveLastElement) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Codice.Client.Common.Platform.GetSymLinkPath (System.String path) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Codice.Client.BaseCommands.BaseCommandsImpl.GetWorkspaceFromPath (System.String path, System.Boolean doPlatformGetSymLinkPath) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Codice.Client.BaseCommands.BaseCommandsImpl.GetWorkspaceFromPath (System.String path) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
PlasticGui.PlasticAPI.GetWorkspaceFromPath (System.String wkPath) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Unity.PlasticSCM.Editor.FindWorkspace.InfoForApplicationPath (System.String path, PlasticGui.IPlasticAPI plasticApi) (at Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/FindWorkspace.cs:36)
Unity.PlasticSCM.Editor.PlasticPlugin.EnableForWorkspace () (at Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/PlasticPlugin.cs:114)
Unity.PlasticSCM.Editor.PlasticPlugin.Enable () (at Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/PlasticPlugin.cs:106)
Unity.PlasticSCM.Editor.UI.CooldownWindowDelayer.EndCooldown () (at Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/UI/CooldownWindowDelayer.cs:56)
Unity.PlasticSCM.Editor.UI.CooldownWindowDelayer.OnUpdate () (at Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/UI/CooldownWindowDelayer.cs:67)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <f85dad9e6fd2410294ff589535912f65>:0)
```

**Comment by WispyMouse** [comment]
Ahoy @LightfootBros ! To get started, can you please provide for me this information:

- What version of Unity are you using?
- What platform are you building your game on? (Windows?)
- What platform are you building your game for? (Standalone Windows?)

I think in order to start helping you debug, I'll need to know what video you're referencing. It likely wasn't made by this team, but if you can link it I can do my best to help grasp what kinds of errors could fall out. Is there a particular point in the video that you started to get the errors at?

Guessing by that first error, InvalidParameters, there's something about your EOS configuration. "InvalidParameters" is a pretty broad error that could be all sorts of things. It's probably trying to run `Init` inside EOSManager and failing at some point there. The configuration files at `Assets/StreamingAssets/EOS/` might be where the issue is at, such as in `EpicOnlineServicesConfig.json`. **Don't share that file with me here, that information is secret and shouldn't be posted here**, but could you please check that the information there is filled out with values from your Epic backend? You should have `productID`, `sandboxID`, `deploymentID`, `clientID`, `clientSecret` all filled out.

I can tell by the constructor of `EOSFriendsManager` failing that the `EOSManager.Instance.GetEOSPlatformInterface.GetFriendsInterface()` is either returning null at `Instance` or returning null at `GetEOSPlatformInterface`. Are there perhaps more logs that you could share, to help understand at what point this is failing to initialize? They'll probably be logs starting with "EOSManager::Init". If you can, please add this symbol to your build's compiler symbols: `ENABLE_DEBUG_EOSMANAGER`. This will give us a little bit more information in logs.

**Comment by LightfootBros** [comment]
Thanks so much for getting back to me, but it seems to have sorted itself
out!!!

**Comment by LightfootBros** [comment]
However, I can log in through the achievements scene but it cannot see my
achievements which are defo set up?

**Comment by WispyMouse** [comment]
Hmm, so your achievements aren't showing, but you're able to authenticate properly? Let's start by making sure your achievements are in the same deployment as you're pointing to in your configuration file. Is it possible you're targeting a different one in your config?

One step for tackling this could be more verbose logging. Please add `ENABLE_DEBUG_EOSACHIEVEMENTMANAGER` as a build symbol, and then at some point before you get achievements, set the logging level. You can do this by calling `EOSManager.Instance.SetLogLevel(LogCategory.Achievements, LogLevel.VeryVerbose);`, which in combination with the above symbol will add more logging. Perhaps something will come out of it that helps us debug?

**Comment by LightfootBros** [comment]
Hi, seems or was My impatience. The achievements had not been pushed to
state, and not they are they are visible. Thanks!

**Comment by WispyMouse** [comment]
It sounds like you're able to see everything now. I'm going to close out this issue - please let us know if you have any other problems, either in here or a new issue. Good luck on your achievement-adventures!

**Comment by LightfootBros** [comment]
Hi,

I do have another issue, when I unlock an achievement in my build (that
just contains the achievement scene) it unlocks but I do not see the
achievement animation. Any ideas why? It just flashes then unlocks

**Comment by LightfootBros** [comment]
These are the error

07/05/2024 15:57:22 LogEOSAuth(Warning): BeginDesktopCrossplayLogin:
Desktop crossplay is not ready:
EOS_DesktopCrossplay_ApplicationNotBootstrapped

07/05/2024 15:57:22 LogEOSAuth(Warning): UserAuthGenerated: Account Portal
overlay failed to load for device auth continuation; falling back to
browser based flow

07/05/2024 15:57:23 LogEOS(Warning): Error response received from backend.
ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>],
HttpStatus=[400],
ErrorCode=[errors.com.epicgames.account.oauth.authorization_pending],
NumericErrorCode=[1012], ErrorMessage=[The authorization server request is
still pending as the end user has yet to visit and enter the verification
code.], CorrId=[EOS-n9Z28QAfR0C60_qKdDlAvQ-HSD78yOSVUuh9JhdTMQFeQ]

07/05/2024 15:57:33 LogEOS(Warning): Error response received from backend.
ServiceName=[StatsAchievements], OperationName=[GetPlayerStats],
Url=[<Redacted>], HttpStatus=[403],
ErrorCode=[errors.com.epicgames.common.policy_missing_action],
NumericErrorCode=[UNSET], ErrorMessage=[Client
xyza7891kBmCwUPRFKBgrc7g9dv2uFMF missing stats:findStatsForLocalUser],
CorrId=[EOS-n9Z28QAfR0C60_qKdDlAvQ-LHjJmDsVNkmj0nV0wQh45Q]

07/05/2024 15:57:34 LogEOSStats(Warning): Failed to get player stats.
Error=EOS_NotConfigured

07/05/2024 15:57:34 LogEOSStats(Warning): EOS_Stats_GetStatsCount - User
not found.

07/05/2024 15:57:34 LogEOS(Warning):
FEpicGamesPlatform::GetOnlinePlatformType - unable to map None to
EOS_OnlinePlatformType

07/05/2024 15:58:03 LogEOS(Warning): Error response received from backend.
ServiceName=[StatsAchievements], OperationName=[GetPlayerStats],
Url=[<Redacted>], HttpStatus=[403],
ErrorCode=[errors.com.epicgames.common.policy_missing_action],
NumericErrorCode=[UNSET], ErrorMessage=[Client
xyza7891kBmCwUPRFKBgrc7g9dv2uFMF missing stats:findStatsForLocalUser],
CorrId=[EOS-n9Z28QAfR0C60_qKdDlAvQ-lfpsM86RN0iJqOVxhgqWqQ]

and this warning\

NullReferenceException: Object reference not set to an instance of an object
CopyToClipboard.CopyOnClick () (at Assets/Samples/Epic Online Services
Plugin for Unity/3.2.1/Standard Pack _ EOS Plugin for Unity
Samples/Scripts/Utility/CopyToClipboard.cs:35)
UnityEngine.Events.InvokableCall.Invoke () (at
<583df70190f94511bd46f12943531dbc>:0)
UnityEngine.Events.UnityEvent.Invoke () (at
<583df70190f94511bd46f12943531dbc>:0)
UnityEngine.UI.Button.Press () (at ***@***.***
/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick
(UnityEngine.EventSystems.PointerEventData eventData) (at
***@***.***/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute
(UnityEngine.EventSystems.IPointerClickHandler handler,
UnityEngine.EventSystems.BaseEventData eventData) (at
***@***.***
/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject
target, UnityEngine.EventSystems.BaseEventData eventData,
UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at
***@***.***
/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at
***@***.***
/Runtime/EventSystem/EventSystem.cs:514)

**Comment by WispyMouse** [comment]
What platform are you building on? The Social Overlay is the component that shows you the "achievement unlocked" animation bit, but that's only available on a subset of platforms; in this repo it'd only be available for Windows builds.

There's a lot of configuration warnings in that block of messages. Were you able to successfully Auth login then Connect login with this user?

**Comment by WispyMouse** [comment]
It's a bit hard to see the full log from the video, but I saw something interesting in the logs.

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/16852552/42a8db78-5b6f-4610-b0f2-f0eabc3fcfd7)

> "Social overlay is disabled due to flags passed to EOS_Platform_Create"

What platform flags are you passing in to the SDK? Please look in `Tools -> EOS Plugin -> EOS Configuration` under `Platform Flags` at the bottom.

Could you pass me your editor log as well? You can find that by opening the `Console` view (by default in the same tab group as `Project`), pressing the three vertical dots at the top right of the tab group, and clicking `Open Editor Log`. I'm hoping that information from there will help me understand where the setup failure or configuration is.

**Comment by WispyMouse** [comment]
Oh! I did just notice the videos are from the Editor. It is expected that the social overlay does not function inside the Editor. I think if the other video was meant to be from a build, it only captured footage from the Editor.

**Comment by LightfootBros** [comment]
Hi,

See link
<https://www.dropbox.com/scl/fo/ckilv4prrszvul87jfdyv/AHM6Awem95P-EXHtR_d6syE?rlkey=49a2mjocrg8xfkt195iw7leyf&dl=0>
to editor logs, screengrab of platform flags (nothing) and editor log

**Comment by WispyMouse** [comment]
Just to check, is this issue occurring in a standalone Windows build? I'm under the impression that since `release 3.2.1`, additional logs are made that say this `is disabled due to flags passed to EOS_Platform_Create` message when running in the Editor. Those messages were a surprise to me, and may make it look like there's a problem while things are working as expected. The social overlay doesn't function in the Editor, so there wouldn't be the achievements animation.

If it's happening in a Windows build, though, we'll have to keep digging! If it happens in a standalone build, we'll need to get logs from the player. After experiencing this error, you can pick up your Unity logs most likely at `%APPDATA%/LocalLow/[yourcompanyname]/[yourproject'sname]/Player.log`.

I'm not seeing any messages from the EOSManager.cs. Can you ensure that either `ENABLE_DEBUG_EOSMANAGER` is defined in your build symbols, or the `//#define ENABLE_DEBUG_EOSMANAGER` line is uncommented in that class?

**Comment by LightfootBros** [comment]
Yes, this is a standalone windows build. Would you like me to invite you to
the project? PlasticSCM? Or can we do a video call? I am getting an error
when putting in (%APPDATA%/LocalLow/[Lightfoot Bros Games]/The Mystery Of
Woolley Mountain/Player.log) but I have added the ENABLE_DEBUG_EOSMANAGER.
It now really isn't working. I'd really appreciate either you jumping in to
the project and having a look or guiding me through a video. I;ve been
trying to get this sorted for two years now. I am close to giving up!

**Comment by WispyMouse** [comment]
I can't do a call, but I can look at your source code! Please upload it to something such as Google Drive, then email a link with permission to read to `eos-support@playeveryware.com`. This will create a ticket on another issue-handling-platform that we manage, and we'll be able to securely help you while using your code. I'll prioritize helping you as soon as we get that!

For the folder position, let's try to adjust that a bit, because even with your code I would like those logs. In Windows, if you type in `%APPDATA%` in to your file explorer, it'll open a special folder location.

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/16852552/8e692985-60bc-4abf-b2a0-40d57dfb117b)
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/16852552/af6354f4-02bc-47b6-a242-d00e2e8b455d)

From here, go up a level (because it will open it to `%APPDATA%/Roaming`), go to `LocalLow`, and find your company name in there. Then navigate to your game inside that, and grab the Player.log file. There shouldn't be any `[` or `]` characters in there, I just included that in the sample link to represent it being a placeholder for your actual values.

**Comment by LightfootBros** [comment]
ok, pc laptop just died. Will re charge and try. ps is Dropbox ok?

**Comment by WispyMouse** [comment]
Since this got handled over Zendesk, I'm going to close out this ticket for now. Let me know by pinging @WispyMouse if you need more assistance, or open a new issue.
