### ISSUE TITLE
EOSManager::Init: InitializePlatformInterface: initResult = AlreadyConfigured

### ISSUE THREAD

**Issue by Buffoverflow** [PlayEveryWare/eos_plugin_for_unity#771]
**Describe the bug**
The second time I enter play mode in Unity I got this message (last message on Editor logs) and Unity stuck on entering play mode:

```
EOSManager::Init: InitializePlatformInterface: initResult = AlreadyConfigured
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at Library/PackageCache/com.playeveryware.eos@f30a908aa2/Runtime/Core/EOSManager.cs:634)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at Library/PackageCache/com.playeveryware.eos@f30a908aa2/Runtime/Core/EOSManager.cs:556)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Samples/Epic Online Services Plugin for Unity/3.2.1/Standard Pack _ EOS Plugin for Unity Samples/Scripts/Core/EOSHostManager.cs:49)

(Filename: Library/PackageCache/com.playeveryware.eos@f30a908aa2/Runtime/Core/EOSManager.cs Line: 634)
```

**To Reproduce**
Unity 2021.3.34f1
put  the Singletons prefab from the samples on the scene and enter play mode the second time

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Unity Editor 
 - Unity Version 2021.3.34f1
 - Plugin Version Release 3.2.1

**Comment by WispyMouse** [comment]
Ahoy @Buffoverflow ! Let's try to solve this problem.

I followed your reproduction steps by getting Unity 2021.3.34f1, getting the Release of the EOS Unity Plugin 3.2.1, made an empty scene and put the Singletons prefab, and then ran the player twice. I reproduced the message - `initResult = AlreadyConfigured` - but what is supposed to happen afterwards if the application is running in the Editor is to unload the library and try to initialize again. It does that successfully for me, without getting stuck.

When you say that Unity gets stuck, what is that experience like? Does the Editor stop responding to clicks and button presses?

Since the EOS SDK is running in native, it can persist through play sessions. It's meant to shut down, but it _should_ be harmless to get this AlreadyConfigured message in the Editor. That suggests that maybe the freeze up is from something happening while trying to unload the library. Is that message you included the last thing visible in the Editor, or the last thing in the Editor log? You can fetch the log from going to the Console tab, clicking on the three vertical dots in the top right of that tab group, and pressing `Open Editor Log`. If there's any logs after that, they might help debug things. If there's not, then we'll have to narrow in on the spot this problem happened. To help with debugging the problem, you might need to put Debug.Log statements inside the functions that are called after this AlreadyConfigured message. That'd be `ShutdownPlatformInterface`, `UnloadAllLibraries`, `ForceUnloadEOSLibrary`, and `LoadEOSLibraries`. Putting a quick log in to each of those might help us determine where the break is.

My colleague mentioned that he's experienced this error before by trying to recompile the C# code while the Editor is running. How consistent is the reproduction of the issue you're getting, and is there any chance this is related?

How did you pull down the EOS Unity Plugin and include it in your project? Did you use the UPM Package?

Hopefully we can get to the bottom issue of this together.

**Comment by Buffoverflow** [comment]
No the last message on the Editor log is the AlreadyConfigured message. The unity freezes the Editor stop responding to clicks and button presses, I had to restart unity after this.

> How consistent is the reproduction of the issue you're getting, and is there any chance this is related?
It always happens on the second play session.

EDIT: not really, it not always happen, I was just doing some tests to send you the logs and I notice that only happens when a I load a second scene. So if I clic play mode and do not change the scene the freeze do not happens.

> How did you pull down the EOS Unity Plugin and include it in your project? Did you use the UPM Package?
I am using the git URL

![Screenshot 2024-07-09 202854](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/7927847/3828ebca-05ac-40b6-b572-eedb45efbfb8)

I am including the full Editor log.

[Editor.log](https://github.com/user-attachments/files/16152250/Editor.log)
[Editor-prev.log](https://github.com/user-attachments/files/16152212/Editor-prev.log)

**Comment by WispyMouse** [comment]
I'll take a more in depth look at this tomorrow, thank you for providing the logs!

When you're loading the second scene, is it additive or single scene mode? Has the Singletons object been marked with DontDestroyOnLoad? Is there another one of the Singleton prefabs in the scene that is transitioned to? Is it at all possible that the Singleton is being destroyed somehow during this operation? Tomorrow, I'll try to reproduce this issue by transitioning to another scene on button press.

Were you able to get any additional logs from putting Debug.Logs at the functions next to that AlreadyConfigured message? There some logs that aren't being printed out here, which you can enable by either going to `EOSManager` and uncommenting the `//#define ENABLE_DEBUG_EOSMANAGER`, or by adding `ENABLE_DEBUG_EOSMANAGER` to your build's symbols.

I strongly doubt this'd cause the problem itself, but something logged might need attention;

> EOS config data does not contain a valid encryption key which is needed for Player Data Storage and Title Storage.

I'll try to see if this could be related by unsetting my own encryption key.

**Comment by Buffoverflow** [comment]
single scene mode.

The singleton is the \Samples\Epic Online Services Plugin for Unity\3.2.1\Standard Pack _ EOS Plugin for Unity Samples\Prefab\Singletons. No changes were made.

![Screenshot 2024-07-09 213550](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/7927847/d2e7613b-8afe-4503-bed0-c89f9368f50f)

> Is there another one of the Singleton prefabs in the scene that is transitioned to?

No

> Is it at all possible that the Singleton is being destroyed somehow during this operation?

I do not think so

> Were you able to get any additional logs from putting Debug.Logs at the functions next to that AlreadyConfigured message?

I can not edit the files, its an external file? Not sure. I amgoing to make a debug session now, lets see.

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/7927847/5446c7fd-137a-4b14-b626-ca7612bcfb07)

I will do a new test with the ENABLE_DEBUG_EOSMANAGER now

> I'll try to see if this could be related by unsetting my own encryption key.

It worth mention that the first play session works perfectly, even the client build works perfectly. The only problem is the second play session after loading the second scene.

**Comment by Buffoverflow** [comment]
I just tested with the Singleton on the second scene and it worked, no stuck on the second play session !!!

After the successful test with the Singleton on the second scene I removed it again for testing and the same error occurred! So yes, if I remove the singleton from the second scene, the second time I play it stucks, and it stucks on this line (ForceUnloadEOSLibrary):

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/7927847/c72c8963-ca66-41ab-b71d-c0920aee9d81)

This is the log with the Singleton on the second scene (successful):
[Editor-Noerror.log](https://github.com/user-attachments/files/16152628/Editor-Noerror.log)

And this is the log after removing the singleton on the second scene:
[Editor.log](https://github.com/user-attachments/files/16152635/Editor.log)

**Comment by WispyMouse** [comment]
Oh yup! I was able to set up a reproduction of this very easily. Loading the next scene in Single mode without the Singletons prefab on the next scene broke it.

I wanna double-check with you; have you marked the Singletons prefab as `DontDestroyOnLoad` in your own code? The prefab won't do that itself. When I marked my Singletons prefab with `DontDestroyOnLoad` and went to the next scene, it didn't crash; without doing that it crashes 100% of the time.

**Comment by WispyMouse** [comment]
Here's what I'm guessing, from doing some sleuthing.

`EOSManager` is a MonoBehaviour, so it gets some messages. The one that's most relevant is its only "wind-down" code, the `OnApplicationQuit`. Whenever you quit from that first scene, with the Singleton prefab in the scene, it will tear down itself using `OnShutdown`. But if you go to another scene, and the prefab doesn't come along or isn't in the next scene, it never does the cleanup. That means native code is still running. Then when the next Singleton prefab instance comes around from you trying to play again, it sees that it's already configured, tries to unload the _still in use Native library code_, and then Unity seizes up and crashes.

We can't make it turn itself `OnDisable` or `OnDestroy`, because we want to support the strategy of having the Singleton prefab in each scene. But clearly, "freezing Unity to the point of it basically crashing" is definitely not what we want! I'll do some more investigation to understand how to avoid this situation.

**Comment by WispyMouse** [comment]
Of course, glad I could help! I'm also glad you were able to help me identify such an annoying problem for our plugin users! I'll be working together with the team to find a solution for this. After some testing, I'm pretty confident that this _exact error_ can only happen in the Editor, at least. Good luck in your dev work! I'm going to close out this issue for now.

**Comment by jollypunch** [comment]
Oh I see. I ran into the same issue, was not aware the singleton didn't mark itself as DontDestroyOnLoad. I assumed it did so. Is this behavior documented?

**Comment by WispyMouse** [comment]
@jollypunch It is not, I think! Looking around our documentation, it's not stated that you must do this.

I've created a task in our back-end tasking to determine if we will make things DontDestroyOnLoad by default, or if we're going to stand by not doing that. Either way, there will be documentation that makes this more clear.
