### ISSUE TITLE
Conflict with Metamask plugin

### ISSUE THREAD

**Issue by Buffoverflow** [PlayEveryWare/eos_plugin_for_unity#791]
**Describe the bug**
Conflict with Metamask plugin. If install both packages I get a compilation error.

I am getting this error after importing the metamask plugin (https://assetstore.unity.com/packages/decentralization/infrastructure/metamask-246786):

`Library\PackageCache\com.playeveryware.eos@f30a908aa2\Runtime\Core\Config.cs(330,13): error CS0518: Predefined type 'System.IAsyncDisposable' is not defined or imported
*** Tundra build failed (1.32 seconds), 317 items updated, 1666 evaluated
Library\PackageCache\com.playeveryware.eos@f30a908aa2\Runtime\Core\Config.cs(330,13): error CS0518: Predefined type 'System.IAsyncDisposable' is not defined or imported`

I dont know its related, but I found this:
https://github.com/atteneder/glTFast/issues/550#issuecomment-1400257136

**To Reproduce**
1. Add eos_plugin_for_unity using the package git URL: https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git
2. Import Metamask plugin

**Expected behavior**
No conflicts should happen

**Screenshots**
![image](https://github.com/user-attachments/assets/f51c5cc2-9059-44fd-9c1f-5f59561bf3c8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Editor
 - Unity Version: 2021.3.34f1
 - Plugin Version: 3.2.1

**Additional context**
I did this on clean project and got the same error. If I install only the metamask plugin it works, no compilation errors. If I install only the eos plugin it works, no compilation errors. The order does not metter, I tried metamask > eos, and eos > metamask

Full editor log:
[Editor.log](https://github.com/user-attachments/files/16276680/Editor.log)

**Comment by WispyMouse** [comment]
Ahoy @Buffoverflow ! I think we can figure this one out together.

`System.IAsyncDisposable` is implemented in both `System.Runtime.dll` as well as a dependency of a dependency of MetaMask. SocketIOUnity has an included `Microsoft.Bcl.AsyncInterfaces.dll` in the project, which is also implements something with the same name. The compiler doesn't know what to do about this situation, with `System.IO.TextWriter` implementing that interface and trying to grab it out of the wrong dll. What we can do about this is help the dll know what is meant to be referenced.

Are you able to modify your MetaMask plugin files and assembly definitions? Here's what worked for me to resolve this error.

- Navigate to Assets -> MetaMask -> Plugins -> Libraries -> SocketIOUnity -> Runtime -> libs. There'll be several .dll files here. Click on `Microsoft.Bcl.AsyncInterfaces` and uncheck "Auto Reference" in the dll's import settings. This will make it so that only `asmdef` files that exactly specify it should be included will be able to use it and see it.
- Go up a level and find `MetaMask.SocketIOUnity.asmdef`. Check "Override References" in its import settings. This will bring up the "Assembly References" UI element. You need to include every assembly this asmdef needs to see, which are:
  - `Microsoft.Bcl.AsyncInterfaces.dll`
  - `Newtonsoft.Json.dll`
  - `System.Text.Json.dll`
  - `System.Reactive.dll`

Can you try that out, and see if it unblocks you?

**Comment by Buffoverflow** [comment]
Hello @WispyMouse,

You are a god! I had to copy the EOS plugin to the package folder and add it to my project manually so I could edit it and fix the issue. I undid this and followed your step-by-step instructions, and it worked like a charm.

This metamask plugin is a pain in the ass, so many different conflicts... I think its now 100% functional.

Thank you so much! I would never have figured it out by myself!

Best regards!

**Comment by WispyMouse** [comment]
Glad I could help! It's always nice when the issue gets solved in one go, huh? Imma close this as resolved, good luck in your work!
