### ISSUE TITLE
What are the steps to connect as Peer to Peer

### ISSUE THREAD

**Issue by KimulatorsFilms** [PlayEveryWare/eos_plugin_for_unity#911]
Hello,

I would like to be able to connect players using Netcode For GameObjects with the EOS Transport. I have looked at the P2PNetcode sample, but I have trouble understanding how it works. 

Normally when using a basic Netcode project, you need to call NetworkManager.Singleton.StartHost(); and NetworkManager.Singleton.StartClient(); I am unsure what needs to be initialize to create a player session with EOS.

With the EOS Transport, how does the client connects to the right host? I believe the client needs the Server User ID to be able to connect to it. Ideally, I would like player to join any sessions not just their friend's session like in the P2PNetcode sample.

If someone could point me to the right steps it will be greatly appreciated.

**Comment by WispyMouse** [comment]
Ahoy @KimulatorsFilms !

We'll be delving in to the `NetworkSamplePlayer` and `UIP2PTransportMenu` that are included with the samples for inspiration on how to approach things. Inside the `Start` function for `UIP2PTransportMenu`, it fetches the Transport manager:

```csharp
EOSManager.Instance.GetOrCreateManager<EOSTransportManager>();
```

`EOSTransportManager` calls out to the function you mentioned, `NetworkManager.Singleton.StartClient`, when you call its own `StartClient()` function. `UIP2PTransportMenu.JoinGame` takes in a `ProductUserId` to try to connect to, and shows what to do when you have that Id. You'll need to get the ProductUserId of the user that is hosting the game. A user that wants to be a host should use their own `EOSTransportManager` and have `StartHost` called on it.

The sample shows connecting to friends because that's what is easiest to fetch for the sample. It sounds like you'd be interested in the plugin's `Session` or `Lobby` features. By using one of these you can set up rooms that can be searched for and joined, which will handle giving you the host's `ProductUserId` when you join one.

The [Sessions walkthrough](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/com.playeveryware.eos/Documentation~/scene_walkthrough/sessions_and_matchmaking_walkthrough.md) and [Lobbies walkthrough](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/com.playeveryware.eos/Documentation~/scene_walkthrough/lobbies_walkthrough.md) are a good starting point. Rule of thumb: If you want EOS to take care of as many things for you as possible, use Lobbies. If you want to have finer control over the lifecycle of an online play session, use Sessions.

Whatcha think? Does this help you get started?

**Comment by KimulatorsFilms** [comment]
Thank you for your answer, I am still a bit unsure. I am using lobbies and so far this is how a player can join a lobby. 
` public void JoinButtonOnClick(Lobby lobbyRef, LobbyDetails lobbyDetailsRef)
    {
        // Join the selected lobby using the lobby and lobbyDetails references
        lobbyManager.JoinLobby(lobbyRef.Id, lobbyDetailsRef, true, UIOnLobbyUpdated);
    }

    // Update the UI when a player joins the lobby
    private void UIOnLobbyUpdated(Result result)
    {
        if (result == Result.Success)
        {
            Debug.Log("Joined lobby successfully!");

            // Update UI to show lobby details
            Lobby currentLobby = lobbyManager.GetCurrentLobby();

            lobbyPanel.SetActive(true);
            lobbyIDText.text = "Joined Lobby ID: " + currentLobby.Id;
        }
        else
        {
            Debug.LogError("Failed to join lobby: " + result);
        }
    }`
    
In my case lobbyManager is a reference to EOSLobbyManager. In EOSLobbyManager.JoinLobby, I see " joinOptions.LocalUserId = EOSManager.Instance.GetProductUserId(); " Is this what you mean by the host's ProductUserId? If so, I am unsure how to use it after to start the client like in the JoinGame method in UIP2PTransportMenu. Any help will be appreciate, thank you!

**Comment by KimulatorsFilms** [comment]
Hello,
I was able to successfully use Lobbies and Peer to Peer connection! Thank you!
