### ISSUE TITLE
How to auto-connect Sample Scenes build when launching from Epic Launcher?

### ISSUE THREAD

**Issue by ulissesnascim** [PlayEveryWare/eos_plugin_for_unity#950]
**Describe the bug**
I'm basically just trying to do 2 things:
1) auto-connect to the user's Epic account when they launch the game from the Epic Launcher
2) trigger Achievement unlocks

That's all! But I can't get past step 1. Because I couldn't get it to happen within my game, I decided to open a new Unity project, configure EOS and build just the Achievements sample scene to see what happens, but that also failed.

**To Reproduce**
1. Start a new Unity project, import the EOS plug-in and configure it in the EOS Configuration window
2. Build the Achievements sample scene
3. Upload to EOS and publish
4. Download the update in the Epic Games Store desktop app connected to your user account.
5. Launch the game and observe that the user account is not connected

**Expected behavior**
Expected the user account to be automatically connected when launching from Epic. Maybe my expectation is incorrect? Can the plug-in achieve what I'm trying to do?

**Screenshots**

**Desktop:**
 - OS: Windows x64
 - Standalone build
 - Unity Version: 2021.3.8f1
 - Plugin Version: 3.3.2

**Additional context**
This is the same issue as [this one](https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/650), however that thread was closed and I couldn't reopen it. Furthermore, the thread's discussion is a bit confusing now as we investigated several other issues in it, so this new one might be better.

#EOS-2169

**Comment by WispyMouse** [comment]
Ahoy @ulissesnascim ! The samples not functioning as desired could be any number of things, so we'll need to go through each of them to hopefully hit where you're at.

## "Automatically Connected"

First thing is we need to check in on your expectations. Is the idea that users will go to login to your game when the game launches, and because you're launching from the Epic Game Store it'd auto log in the user without them needing to explicitly login? If so, try to use the `ExchangeCode` login type.

```csharp
// This is inside UILoginMenu.OnLoginButtonClick()
// Note how it gets the "auth password" from the command line arguments; those are only available when you've launched your game through the Epic Game Store
else if (loginType == LoginCredentialType.ExchangeCode) 
{
    EOSManager.Instance.StartLoginWithLoginTypeAndToken(loginType,
                                                           null,
                                                           EOSManager.Instance.GetCommandLineArgsFromEpicLauncher().authPassword,
                                                           StartLoginWithLoginTypeAndTokenCallback);
}
```

The samples aren't presently set up to "automatically" log in a user, even if you've launched from the store. If you run the above, it's the equivalent of selecting "ExchangeCode" from the login type drop down and trying to log in.

## Configure EOS

Check that your plugin is configured for *your game*. Have you replaced things like the `Client ID` and `Product ID` in the `Tools -> EOS Plugin -> EOS Configuration` popup? The samples in the repo point at our demo project, but you'll need to manually insert your own information to use it.

When you launch a game through the Epic Game Store, it provides a `-epicsandboxid` and `-epicdeploymentid` argument into your game. The EOS Plugin for Unity reads those overrides, and uses them instead of the sandbox and deployment information you configured in the popup. Are you using a Dev/Staging environment in your published game? If so, the changes will apply to that sandbox, not to the live one.

## Auto-"Connect"

Are you creating a connect user through the usual login flow? The samples handle their login through the `UILoginMenu.cs` class. In most authentication cases it performs;

- An Auth login using your provided credentials, through `StartLoginWithLoginTypeAndTokenCallback`.
- If that Auth fails with the result of `Result.InvalidUser`, it uses `EOSManager.Instance.AuthLinkExternalAccountWithContinuanceToken` to create the user in EAS.
- Attempt a Connect login with `StartConnectLoginWithEpicAccount`.
- If that connect login fails with `Result.InvalidUser`, it uses `CreateConnectUserWithContinuanceToken` to create the user, then tries to login again.

If you're using our sample code, then all the above should happen for you.

**Comment by ulissesnascim** [comment]
Thank you @WispyMouse, it works! I had misunderstood the use case for ExchangeCode when reading the docs and testing.

Note: this solution does result in the "auto-connect" behaviour I wanted, although it requires a permission from the user (which seems a little unnecessary when launching from Epic, compared to launching from Steam for example, but it's fine).

I'll go back to my main project and make the changes to get auto-connect working with your script. Thanks again, this was super helpful!
